/**
 * Created by Administrator on 2016/8/19.
 */
export const START_FETCH = 'START_FETCH';
export const END_FETCH = 'END_FETCH';
export const START_REFRESH = 'START_REFRESH';
export const END_REFRESH = 'END_REFRESH';

/*
 * Users
 * */
export const USER_LIST_START = 'USER_LIST_START';
export const USER_LIST_END = 'USER_LIST_END';
export const USER_MANAGER_LIST_START = 'USER_MANAGER_LIST_START';
export const USER_MANAGER_LIST_END = 'USER_MANAGER_LIST_END';
export const USER_SAVE_START = 'USER_SAVE_START';
export const USER_SAVE_END = 'USER_SAVE_END';
export const USER_DETAIL_START = 'USER_DETAIL_START';
export const USER_DETAIL_END = 'USER_DETAIL_END';
export const USER_DELETE_START = 'USER_DELETE_START';
export const USER_DELETE_END = 'USER_DELETE_END';
export const USER_COUNT_OF_MANAGER_START = 'USER_COUNT_OF_MANAGER_START';
export const USER_COUNT_OF_MANAGER_END = 'USER_COUNT_OF_MANAGER_END';
export const SEND_EMAIL_START = 'SEND_EMAIL_START';
export const SEND_EMAIL_END = 'SEND_EMAIL_END';